name: otoplus_example
description: "A otoplus example app"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  get_it: ^7.7.0
  injectable: ^2.4.1
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1


flutter:


  uses-material-design: true
